### ISSUE TITLE
Unpaid Orders still go through

### ISSUE THREAD

**Issue by WilsonMF** [bitpay/zencart-plugin#13]
This plugin seems to have a flaw to it or I am doing something wrong. The problem is that once a shopper places an order (hits the confirm button) the shopper is presented with the bitpay screen and offered a chance to make payment. If he or she decides they do not want to continue with the purchase, perhaps they don't have enough bitcoin and didn't realize it, there is no way to cancel the order and if they just close out the screen the order is still pending in zen cart. The module should not be generating an order until payment has been made or have some means to cancel the order and clear the cart. The bitpay api seems to have enough flexibility to accomplish this as in checking the status of an invoice.

**Comment by ionux** [comment]
Thanks for reporting this issue, @WilsonMF.  Are you still having this issue?

**Comment by philosodad** [comment]
This is a known issue in the plugin that will be fixed in version 2.0.

**Comment by ionux** [comment]
Roger that!  Closing this issue then.
