### ISSUE TITLE
BTC conversion

### ISSUE THREAD

**Issue by maartenvonz** [bitpay/zencart-plugin#19]
I created a currency in Zencart for Bitcoin (BTC)

I set an exchange rate at 0.00161290:1. (In my case it is BTC to £, and the GBP being the default currency.)

When testing a purchase of a product for BTC 0.0161, the plugin sends an amount of over $700 to Bitpay.

From the email: 
An invoice for $762.23 could not be created because its value exceeds your current approved volume of $100 per day, and $500 per year.

**Comment by maartenvonz** [comment]
Further information from the log file:

[03-Dec-2016 19:51:10 Europe/London] createInvoice error array (
  'type' => 'limitExceeded',
  'message' => 'Invoice not created due to account limits, please check your approval levels',
)
[03-Dec-2016 19:51:10 Europe/London] PHP Fatal error:  Call to undefined function zen_remove_order() in ******/public_html/includes/modules/payment/bitpay.php on line 158

**Comment by ajp8164** [comment]
Merchant can set fx rates wrong.. not a bug, merchant issue
